n<-readline(prompt="Enter value of n = ")
n<-as.integer(n)
r<-readline(prompt="Enter value of r (r<n) = ")
r<-as.integer(r)
source("Mathematical\\fact.R")
f1<-fact(n)
f2<-fact(r)
f3<-fact(n-r)
c<-f1/(f2*f3)
cat("nCr = ",c)
